### ISSUE TITLE
Improvement to "working-with-stacks" guide

### ISSUE THREAD

**Issue by nastacio** [kabanero-io/guides#11]
The "working-with-stacks" guide is good as it is, so this is an enhancement request rather than a defect.

I came across a more comprehensive customization example (https://kabanero-workshop-nodejs.mybluemix.net/guides/dev-getting-started/#stack-scenario-2-add-the-helmet-traffic-handler-to-the-stack) , which I think better illustrates the potential of stack customization, with a change to both `server.js` and the `package.json` files that improve the overall security of the stack.

The current example only changes the default application template and does not make any modifications to the actual stack.

**Comment by SueChaplain** [comment]
Thanks for this @nastacio - I picked a very simple example in order to get the guide out, so this will be a great improvement.
