### ISSUE TITLE
"Creating a stack hub" guide does not completely explain how to configure deployment environment

### ISSUE THREAD

**Issue by nastacio** [kabanero-io/guides#19]
Looking at the "Configuring your deployment environment" section of the ["Creating a stack hub" guide](https://kabanero.io/guides/creating-a-stack-hub/#configuring-your-deployment-environment) there a few things that are hard to follow:

"You must update your Kubernetes operator custom resource (CR) definition file to reference your stack hub index file."   

1. Which CR? There are so many in Kubernetes. I am guessing this should be Kabanero instead of Kubernetes, but unclear as I have never executed these steps?

1. Where is that "Kubernetes operator custom resource (CR) definition file" located? Was it created in another guide (presumably installation) ? If so, a link to the guide would be helpful. As a reader, I would not know where to find that file. I know I could use `kubectl get <some type, name, or label> -o yaml` to get a copy of the existing file or `kubectl patch ...`, but I don't know what the selection criteria would be.

1. Once I make that edit, then what? Apply it back with `kubectl apply ...`? I am guessing that, at a minimum, yes, but unclear if anything else is needed, such as "waiting a few moments" or <restarting something>. Should there be a verification step, such as a kabanero CLI invocation or kicking off a new build using the new stack?

cc @SueChaplain , @groeges

**Comment by groeges** [comment]
@nastacio Answers to some of the questions and possible updates to the guide:

1. Yes, this is the Kabanero operator custom resource (CR). This is mentioned / installed in the last step (step 4) of the Kabanero scripted installation instructions: https://kabanero.io/docs/ref/general/installation/installing-kabanero-foundation.html#scripted-installation 
2. I presume we could point to the docs relating to  https://kabanero.io/docs/ref/general/configuration/kabanero-cr-config.html especially this section https://kabanero.io/docs/ref/general/configuration/kabanero-cr-config.html#inspecting-your-kabanero-cr-instance
3. Yes, once edited you re-apply the file "oc apply -f kabanero.yaml -n kabanero"

@SueChaplain We might want to expand the guide with some of this info.

**Comment by nastacio** [comment]
I came back to attempt the updated instructions, which is also the first time I attempt the instructions at all, but I got stuck/blocked on the first step:

```
git clone https://github.com/kabanero/kabanero-stack-hub.git
Cloning into 'kabanero-stack-hub'...
remote: Repository not found.
```

cc @groeges , @SueChaplain

**Comment by nastacio** [comment]
I see, the command should use the path `kabanero-io` instead of `kabanero`, like this:

```
git clone https://github.com/kabanero-io/kabanero-stack-hub.git
```

**Comment by SueChaplain** [comment]
@nastacio - I fixed the bad URL - thanks! The deploying section actually applies to 2 guides, "Working with stacks" and "Creating a stack hub", so I made the changes Steve approved in both. I've also tried to connect these guides a bit better, so they now reference one another. All the changes are in https://github.com/kabanero-io/guides/pull/21
