### ISSUE TITLE
Improve "Creating a stack hub guide" to help a customer apply this to their own GitHub

### ISSUE THREAD

**Issue by SueChaplain** [kabanero-io/guides#23]
[Creating a stack hub](https://kabanero.io/guides/creating-a-stack-hub/) guide

Review comment from Jarek:

What's missing is how the customer can clone this to their own github and host the index.yaml. Today the guide says "This index file should be hosted somewhere that is accessible to developers, such as a GitHub repository",  but we don't actually say how to do that. So, would be good to add something for that or have another guide for it

**Comment by groeges** [comment]
@SueChaplain Can you add a link to the guide?
