### ISSUE TITLE
Reorganize guide categories

### ISSUE THREAD

**Issue by jantley-ibm** [kabanero-io/guides#28]
Proposal for new guide categories on Kabanero:

UI Title: **Getting started**
category name: **basic**
- Developing with the Command Line Interface (CLI) - *current category **basic***
- Developing with Codewind and VS Code - *current category **stacks***
- Developing with Codewind and Eclipse - *current category **stacks***
- Customizing application stacks - *current category **stacks***
- Creating a stack hub - *current category **stacks***

UI title: **Developing with stacks** 
category name: **stacks**
- Developing with the Open Liberty stack - *current category **stacks***
- Developing with the SpringBoot stack - *current category **stacks***
- Developing with the Eclipse Microprofile stack - *current category **stacks***
- Developing with the Node.js stack - *current category **stacks***
- Developing with the Node.js Express stack - *current category **stacks***

UI title: **Building and deploying applications**
category name: **pipelines**
- Building and deploying applications with pipelines - *current category **pipelines***
- Creating and updating tasks and pipelines - *current category **pipelines***

UI title: **Managing the environment** 
category name: **manage**
- Using kAppNav - *missing most front matter*
- Application monitoring with Prometheus and Grafana (x2) - *missing most front matter*
- Application logging with Elasticsearch, Fluentd, and Kibana (x2) - *current category OCP **basic**, OKD missing front matter*
- Jenkins integration - *missing most front matter*
- Nexus integration - *missing category*

UI title: **More guides**
category name: not sure if there is one, isn't this the default for guides that don't have a category?

**Comment by jantley-ibm** [comment]
@alohr let us know if you agree with this reorganization.  We can then coordinate the updating of the guide metadata with whatever work you need to do on your side.

**Comment by alohr51** [comment]
reorg looks good to me, we'll just need to sync an update to the website with these changes since the categories on the website UI will need to change

**Comment by mingcyu** [comment]
Adding @j-c-berger as an interested party

**Comment by SueChaplain** [comment]
Basic category fixed with https://github.com/kabanero-io/guides/pull/37

**Comment by SueChaplain** [comment]
Nexus integration category added in PR https://github.com/kabanero-io/guide-nexus-repository-integration/pull/9 .... awaiting review from Steven Hung before moving across to guides repo.

**Comment by jantley-ibm** [comment]
closing as completed in Kabanero 0.8
