### ISSUE TITLE
Make events-operator guide self contained

### ISSUE THREAD

**Issue by mchenggit** [kabanero-io/guides#73]
Updates in: https://github.com/kabanero-io/events-operator/tree/prototype#kabanero-integration

Currently the guide omits some of the steps required to configure secrets for Tekton. It has been updated to be self contained, so that user can set up a successful run just by following the guide. The major changes are:
- changing some of the sample yamls with different names
- Added a new section about switching to kabanero project at the beginning of the guide
- Added new sub-section on configuring image registry secret
- Added new sub-section about updating pipeline service account
- Making the default value for the variable body.webhooks-tekton-local-deploy "true"

**Comment by SueChaplain** [comment]
See https://github.com/kabanero-io/guides/pull/71 for changes
