### ISSUE TITLE
Guides for 0.6.0 need concrete references to Kabanero repositories

### ISSUE THREAD

**Issue by nastacio** [kabanero-io/guides#8]
The 0.6.0 guides for Kabanero started referencing an abstract “acme” stack repo (e.g. https://kabanero.io/guides/collection-nodejs).

I am told the references to the `kabanero` appsody repo were abstracted to represent other potential sources of stacks, but abstractions do not work well for guides.

```
Next, run the following command to add the URL for your stack configuration file:
appsody repo add <my-org-stack> <URL>
```

Since this is a basic guide, new users playing with the technology don’t have “my-org-stack” at that point and the instructions turn into a dead-end.

There is a clever verbal if-else segue in the next paragraph to get the reader back on track:

```
If you do not have a stack hub that contains customized, pre-configured application stacks, you can skip to Initializing your project and develop your app based on the public application stack for Node.js.
```

The previous statement leads me to the next problem with the approach: If the user _does_ have a customized stack hub, there is no guarantee that the subsequent instructions will work, since they assume the stack configuration and code template shipped in the current Kabanero stacks. 

Besides the confusion, the worst problem  here is that if the user goes with the appsody incubator stacks, they will later hit this message when attempting to build the app with Tekton:

```
The Kabanero collection contained in docker.io/appsody/<stack_name> is not active on this system and cannot be built"
```
My suggestion here is to always use concrete and verifiable sequences of steps that are guaranteed to work and include wording to characterize the `kabanero` repositories as being an example and explaining that developer organizations will most likely customize existing stacks and advertise different stack URLs that developer in the organization would use.

**Comment by SueChaplain** [comment]
One guide updated for review. Once agreed, changes will be replicated across the others.
